/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef client_service_CONSTANTS_H
#define client_service_CONSTANTS_H

#include "client_service_types.h"

namespace celestial {

class client_serviceConstants {
 public:
  client_serviceConstants();

};

extern const client_serviceConstants g_client_service_constants;

} // namespace

#endif
