/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "raft_service_constants.h"

namespace celestial {

const raft_serviceConstants g_raft_service_constants;

raft_serviceConstants::raft_serviceConstants() {
}

} // namespace

