/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef raft_service_CONSTANTS_H
#define raft_service_CONSTANTS_H

#include "raft_service_types.h"

namespace celestial {

class raft_serviceConstants {
 public:
  raft_serviceConstants();

};

extern const raft_serviceConstants g_raft_service_constants;

} // namespace

#endif
