/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "client_service_constants.h"

namespace celestial {

const client_serviceConstants g_client_service_constants;

client_serviceConstants::client_serviceConstants() {
}

} // namespace

